[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_earna = "2me2g1K7KVA7RBhg1rcbpxRvCknd4v1UCA8RMEjm3hmg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anodaram/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
